apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab03
  namespace: labs
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lab03
  template:
    metadata:
      labels:
        app: lab03
    spec:
      containers:
      - name: lab03-container
        image: htcl/htis-web-app:v1.0.2
        ports:
        - containerPort: 80
